AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for storing file metadata.

Resources:

  MyFilesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: FileApiFiles
      AttributeDefinitions:
        - AttributeName: fileId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: fileId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserIdIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
          - Key: Environment
            Value: Dev

Outputs:

  FilesTableName:
    Description: DynamoDB table name
    Value: !Ref FileApiFiles