AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket for MVP file storage.

Resources:

  MyFileBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub fileapi-storage-${AWS::AccountId}-dev
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      Tags:
        - Key: Environment
          Value: Dev

Outputs:

  FileBucketName:
    Description: Bucket name created
    Value: !Ref MyFileBucket