spring.application.name=cloudfile-processor
server.port=8080
spring.config.import=aws-parameterstore:/file-processor/dev/
spring.security.oauth2.resourceserver.jwt.issuer-uri=${/file-processor/dev/cognito/issuer-uri}
cognito.client-id=${/file-processor/dev/cognito/client-id}
spring.profiles.active=dev