spring.application.name=cloudfile-processor
server.port=8080

app.aws.region=us-east-1
app.s3.input-bucket-name=${/file-processor/dev/input-bucket-name}
app.s3.output-bucket-name=${/file-processor/dev/output-bucket-name}
app.s3.presigned-url-expiration-minutes=15