spring.application.name=cloudfile-processor
spring.config.import=aws-parameterstore:/file-processor/dev/
spring.profiles.active=dev
spring.security.oauth2.resourceserver.jwt.issuer-uri=${/file-processor/dev/cognito/issuer-uri}
cognito.client-id=${/file-processor/dev/cognito/client-id}

security.oidc.enabled=true